### ISSUE TITLE
hello?

### ISSUE THREAD

**Issue by otgo** [catwell/lua-multipart-post#4]

**Comment by catwell** [comment]
Hello @otgo :) Did you want something ?

**Comment by tst2005** [comment]
Probably ask if somebody know what he had wanted to ask.

**Comment by otgo** [comment]
XD
Can you add support for arrays?
I need to upload a file inside an array

**Comment by catwell** [comment]
What do you mean upload a file inside an array?

Do you have an example of the API you want to call, or code in another language that does it?

**Comment by otgo** [comment]
Exm, upload a file here:

`https://domain.name/api.php?data_file={"name":"hello", "file":"myfile.jpg"}`

`https://domain.name/api.php?data_files=[{"name":"hello", "file":"myfile.jpg"}, {"name":"hello", "file":"myfile.jpg"}]`

[API Example](https://core.telegram.org/bots/api#sendmediagroup)

Myfile.jpg will.be the file

**Comment by catwell** [comment]
You can already use the API from your example.

`media` is a json-serialized array which you create e.g. like this:

```lua
media = json.encode {
    {type = "photo", media = "attach://photo_1", caption = "photo 1"},
    {type = "photo", media = "attach://photo_2", caption = "photo 2"},
}
```

And then you do this:

```lua
local rq = multipart_post.gen_request {
    photo_1 = {name = "photo1.jpg", data="..."},
    photo_2 = {name = "photo2.jpg", data="..."},
    media = media,
}
```

**Comment by otgo** [comment]
Ohhh! it's works hahaha, thankss!
