### ISSUE TITLE
Will this work with Lua 5.1

### ISSUE THREAD

**Issue by nodecentral** [catwell/lua-multipart-post#8]
Hi

hope you’re well, 

As I’m still reasonably new to all things Lua, id like to use this on embedded system running 5.1, is it compatible ?

If not , do you know what I’d need to change to make it work ?

**Comment by catwell** [comment]
Hello,

it works with Lua 5.1, I am not sure about your embedded system though. Does it already run LuaSocket? If so it should be fine.

**Comment by nodecentral** [comment]
Many thanks for responding, the embedded system does indeed have luasockets, and most core abilities, plus I can add new modules, although the ones I’ve seen start with something like `module("modulename", package.seeall)`

do I just add a line like that to the top of your module file ?

**Comment by catwell** [comment]
No, that is an old way to define modules in Lua 5.1 but the new way I use in that module also works. You just need to assign the result of the `require` call to a variable because this module does not create a global.

**Comment by nodecentral** [comment]
Thanks @catwell I'm still learning Lua, but I think I know what you mean.

Would it be something like this ?
````
local multipart-post = require("multipart-post")

````

**Comment by catwell** [comment]
Yes, except you cannot name the variable `multipart-post` because dashes are not valid in Lua variable names. So for instance:

```lua
local multipart_post = require("multipart-post")
```

If you want to make it a global (available everywhere in your application) remove the `local` keyword:

```lua
multipart_post = require("multipart-post")
```

For more details: https://github.com/catwell/lua-multipart-post#usage

**Comment by nodecentral** [comment]
Thanks again @catwell , 

Just so I’m clear, i will need to put `multipart_post = require("multipart-post") ` at the very top of your `multipart-post.lua` file before i upload it ? 

If it helps, I’d be trying to convert this curl command 
````
curl -H "Authorization: Basic Y2hyaXM62tgbsgjunotmeY2hyaXNob3N0aW5n" -F "title=Companies House File 10" -F "correspondent=12" -F "document=@/mnt/nas/10.pdf" http://192.168.102.134:8777/api/documents/post_document/
````
Into Lua code, more just to help me in my Lua learning curve..

What I thought would be reasonably straight forward thing to do, has turned out to be quite the opposite :-) Sending a multipart form data submission via http.request, is not as straight forward as I hoped (see my failed attempt below) so I’m looking forward to seeing what it looks like with your module..

(If you can see where i went wrong with the following, i appreciate any corrections)
````
local http = require("socket.http")
local ltn12 = require("ltn12")
local mime = require("mime")
local lfs = require("lfs")

local username = "username"
local password = "password"

local httpendpoint = 'http://httpbin.org/post'
local filepath = "/mnt/nas/10.pdf"
local file = io.open(filepath, "rb")
local contents = file:read( "*a" )

-- https://stackoverflow.com/questions/3508338/what-is-the-boundary-in-multipart-form-data

local boundary = "-----BoundaryePkpFF7tjBAqx29L"
local send = "--"..boundary..
            "\r\nContent-Disposition: form-data; title='Companies House File'\r\n"
			.."----"..boundary..
			"\r\nContent-Disposition: form-data; document="..filepath..
            "\r\nContent-type: application/pdf".."\r\n"
			..contents.."\r\n"
			.."------"..boundary.."--\r\n"

-- Execute request (returns response body, response code, response header)

local resp = {}
local body, code, headers, status = http.request {
    url = httpendpoint,
    method = 'POST',
    headers = {
		["Authorization"] = "Basic " .. (mime.b64(username ..":" .. password)),
		["Content-Length"] = lfs.attributes(filepath, 'size'),
		['Content-Type'] = "multipart/form-data; boundary="..boundary,
    },
   -- source = ltn12.source.file( io.open(filepath,"rb") ),
   source = ltn12.source.file( io.open(send) ),
    sink = ltn12.sink.table(resp)
}

print(body, code, headers, status)
print(table.concat(resp))

if headers then 
    for k,v in pairs(headers) do 
        print(k,v) 
    end
end
````

**Comment by catwell** [comment]
Hello @nodecentral and sorry for the late answer.

No you should not modify `multipart-post.lua` at all. You put that in *your* code using the module.

Regarding your code example, if you want to do it by hand, it is not easy to test because that API is not public but there are several things wrong in it. Most importantly this line makes no sense:

```lua
source = ltn12.source.file( io.open(send) ),
```

`send` is not a filename, you should probably use `ltn12.source.string`.

But if you do not know Lua well I suggest you try to use the module instead... Look at examples in the readme and in `multipart-post.test.lua`

**Comment by nodecentral** [comment]
Thanks again @catwell 

the code I shared earlier was one of many attempts and perhaps that one was not the best example to share. I’ve looked at your code to see if I can work out what’s missing and I’ve tried a few things, which has resulted in a bit of progress the main thing is that I can send the file, the only gap is the form entry parts - see below (it feels like I’m in touching distance, so hopefully you can see the tweak that’s needed..

````
local http = require("socket.http")
local ltn12 = require("ltn12")
local lfs = require "lfs"
http.TIMEOUT = 5

local function upload_file ( url, filename )
    local fileHandle = io.open( filename,"rb") 
    local fileContent = fileHandle:read( "*a" )
    fileHandle:close()
	
    local boundary = 'abcd'
	
    local header_b = 'Content-Disposition: form-data; name="document"; filename="' .. filename .. '"\r\nContent-Type: text/plain\r\n'
	local header_c = 'Content-Disposition: form-data; name="title"\r\n"Companies House File"\r\n'
	local header_d = 'Content-Disposition: form-data; name="correspondent"\r\n"12"\r\n'
	
    local MP_b = '--'..boundary..'\r\n'..header_b..'\r\n'..fileContent..'\r\n--'..boundary..'--\r\n'
	local MP_c = '--'..boundary..'\r\n'..header_c..'\r\n--'.. boundary..'--\r\n'
	local MP_d = '--'..boundary..'\r\n'..header_d..'\r\n--'.. boundary..'--\r\n'
	
	local MPCombined = MP_b..MP_c..MP_d
		
    local   response_body = { }
    local   _, code = http.request {
            url = url , 
            method = "POST",
            headers = {    ["Content-Length"] =  MPCombined:len(), 
                           ['Content-Type'] = 'multipart/form-data; boundary=' .. boundary    
                         },
            source = ltn12.source.string(MPCombined) ,         
            sink = ltn12.sink.table(response_body),
                }
     return code, table.concat(response_body)
end

 local rc,content = upload_file ('http://httpbin.org/post', '/mnt/nas/10.pdf' ) 
 print(rc,content)
 ````

**Comment by catwell** [comment]
Hello @nodecentral.

If you want to do this manually I have fixed your code in [this gist](https://gist.github.com/catwell/c79055d007760b3c89ecd9240f34fb89). Check out [the diff](https://gist.github.com/catwell/c79055d007760b3c89ecd9240f34fb89/revisions) to see what I changed.

If you wanted to use this module instead (which is simpler and less error-prone) here is how you could do it for instance:

```lua
local multipart_post = require "multipart-post"
local http = require "socket.http"
local ltn12 = require "ltn12"

local function upload_file(url, filename)
    local fileHandle = io.open(filename, "rb")
    local fileContent = fileHandle:read("*a")
    fileHandle:close()

    local rq = multipart_post.gen_request({
        document = {
            name = filename,
            data = fileContent,
            content_type = "application/pdf",
        },
        title = "Companies House File",
        correspondent = "12",
    })

    local response_body = {}
    rq.url = "http://httpbin.org/post"
    rq.sink = ltn12.sink.table(response_body)
    local _, code = http.request(rq)
    return code, table.concat(response_body)
end

local rc, content = upload_file("http://httpbin.org/post", "/mnt/nas/10.pdf")
print(rc, content)
```

Also note that this which is adapted from your code loads the whole file in memory. Since you're in an embedded use case you may want to use [ltn12 streaming](https://github.com/catwell/lua-multipart-post#advanced-usage) instead:

```lua
local multipart_post = require "multipart-post"
local http = require "socket.http"
local ltn12 = require "ltn12"

local function upload_file(url, filename)
    local file = io.open(filename, "rb")
    local file_length = file:seek("end")
    file:seek("set", 0)

    local rq = multipart_post.gen_request({
        document = {
            name = filename,
            data = file,
            len = file_length,
            content_type = "application/pdf"
        },
        title = "Companies House File",
        correspondent = "12",
    })

    local response_body = {}
    rq.url = "http://httpbin.org/post"
    rq.sink = ltn12.sink.table(response_body)
    local _, code = http.request(rq)
    return code, table.concat(response_body)
end

local rc, content = upload_file("http://httpbin.org/post", "/mnt/nas/10.pdf")
print(rc, content)
```

**Comment by nodecentral** [comment]
Wow, thanks so much @catwell !!

Comparing my code to your git post, it  looks like I wasn’t  too far away - unfortunately when you work on something for so long as I did, you don’t sometimes notice the obvious things..  

It’s also good to see now how your module works vs my code..

huge thanks again !!
